name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go: [oldstable, stable]
        os: [ubuntu-latest, macos-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0

      - uses: actions/setup-python@v5

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Clear pre-commit cache
        run: rm -rf ~/.cache/pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Test with Go
        run: go test -race ./...
