name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go: [oldstable, stable]
        os: [ubuntu-latest, macos-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0

      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - name: Test with Go
        run: go test -race -json ./... > TestResults-${{ matrix.os }}-${{ matrix.go }}.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.os }}-${{ matrix.go }}
          path: TestResults-${{ matrix.os }}-${{ matrix.go }}.json
